base_url = "bricklaying.art"
title = "bricklaying"
description = "can the heart beat without the soul?"
compile_sass = true
build_search_index = false

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-dark"
